# Supabase SDK Configurations
# Defines SDK sources and output settings with multi-version support

sdks:
  javascript:
    name: "JavaScript"
    language: javascript
    versions:
      v2:
        display_name: "Supabase JavaScript Client v2"
        spec:
          url: "https://raw.githubusercontent.com/supabase/supabase/master/apps/docs/spec/supabase_js_v2.yml"
          local_path: null
          format: "openref-0.1"
        output:
          base_dir: "javascript"
          filename_prefix: "supabase-js-v2"
      v1:
        display_name: "Supabase JavaScript Client v1"
        spec:
          url: "https://raw.githubusercontent.com/supabase/supabase/master/apps/docs/spec/supabase_js_v1.yml"
          local_path: null
          format: "openref-0.1"
        output:
          base_dir: "javascript"
          filename_prefix: "supabase-js-v1"

  kotlin:
    name: "Kotlin"
    language: kotlin
    versions:
      v3:
        display_name: "Supabase Kotlin Client v3"
        spec:
          url: "https://raw.githubusercontent.com/supabase/supabase/master/apps/docs/spec/supabase_kt_v3.yml"
          local_path: null
          format: "openref-0.1"
        output:
          base_dir: "kotlin"
          filename_prefix: "supabase-kt-v3"
      v2:
        display_name: "Supabase Kotlin Client v2"
        spec:
          url: "https://raw.githubusercontent.com/supabase/supabase/master/apps/docs/spec/supabase_kt_v2.yml"
          local_path: null
          format: "openref-0.1"
        output:
          base_dir: "kotlin"
          filename_prefix: "supabase-kt-v2"
      v1:
        display_name: "Supabase Kotlin Client v1"
        spec:
          url: "https://raw.githubusercontent.com/supabase/supabase/master/apps/docs/spec/supabase_kt_v1.yml"
          local_path: null
          format: "openref-0.1"
        output:
          base_dir: "kotlin"
          filename_prefix: "supabase-kt-v1"

  dart:
    name: "Dart"
    language: dart
    versions:
      v2:
        display_name: "Supabase Dart/Flutter SDK v2"
        spec:
          url: "https://raw.githubusercontent.com/supabase/supabase/master/apps/docs/spec/supabase_dart_v2.yml"
          local_path: null
          format: "openref-0.1"
        output:
          base_dir: "dart"
          filename_prefix: "supabase-dart-v2"
      v1:
        display_name: "Supabase Dart/Flutter SDK v1"
        spec:
          url: "https://raw.githubusercontent.com/supabase/supabase/master/apps/docs/spec/supabase_dart_v1.yml"
          local_path: null
          format: "openref-0.1"
        output:
          base_dir: "dart"
          filename_prefix: "supabase-dart-v1"

  csharp:
    name: "C#"
    language: csharp
    versions:
      v1:
        display_name: "Supabase C# Client v1"
        spec:
          url: "https://raw.githubusercontent.com/supabase/supabase/master/apps/docs/spec/supabase_csharp_v1.yml"
          local_path: null
          format: "openref-0.1"
        output:
          base_dir: "csharp"
          filename_prefix: "supabase-csharp-v1"
      v0:
        display_name: "Supabase C# Client v0"
        spec:
          url: "https://raw.githubusercontent.com/supabase/supabase/master/apps/docs/spec/supabase_csharp_v0.yml"
          local_path: null
          format: "openref-0.1"
        output:
          base_dir: "csharp"
          filename_prefix: "supabase-csharp-v0"

  python:
    name: "Python"
    language: python
    versions:
      v2:
        display_name: "Supabase Python Client v2"
        spec:
          url: "https://raw.githubusercontent.com/supabase/supabase/master/apps/docs/spec/supabase_py_v2.yml"
          local_path: null
          format: "openref-0.1"
        output:
          base_dir: "python"
          filename_prefix: "supabase-py-v2"

  swift:
    name: "Swift"
    language: swift
    versions:
      v2:
        display_name: "Supabase Swift SDK v2"
        spec:
          url: "https://raw.githubusercontent.com/supabase/supabase/master/apps/docs/spec/supabase_swift_v2.yml"
          local_path: null
          format: "openref-0.1"
        output:
          base_dir: "swift"
          filename_prefix: "supabase-swift-v2"
      v1:
        display_name: "Supabase Swift SDK v1"
        spec:
          url: "https://raw.githubusercontent.com/supabase/supabase/master/apps/docs/spec/supabase_swift_v1.yml"
          local_path: null
          format: "openref-0.1"
        output:
          base_dir: "swift"
          filename_prefix: "supabase-swift-v1"
